package com.imory.cn.company.dto;

import java.util.Date;

public class CompanyTransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.id
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.fileId
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.recentlyNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Double recentlyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.recentlyDirection
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private String recentlyDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.recentlyDate
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private String recentlyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.yearNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Double yearNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.repertoryNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Double repertoryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.orderNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.createTime
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_transfer.creator
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    private Integer creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.id
     *
     * @return the value of company_transfer.id
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.id
     *
     * @param id the value for company_transfer.id
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.fileId
     *
     * @return the value of company_transfer.fileId
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.fileId
     *
     * @param fileId the value for company_transfer.fileId
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.recentlyNum
     *
     * @return the value of company_transfer.recentlyNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Double getRecentlyNum() {
        return recentlyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.recentlyNum
     *
     * @param recentlyNum the value for company_transfer.recentlyNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setRecentlyNum(Double recentlyNum) {
        this.recentlyNum = recentlyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.recentlyDirection
     *
     * @return the value of company_transfer.recentlyDirection
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public String getRecentlyDirection() {
        return recentlyDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.recentlyDirection
     *
     * @param recentlyDirection the value for company_transfer.recentlyDirection
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setRecentlyDirection(String recentlyDirection) {
        this.recentlyDirection = recentlyDirection == null ? null : recentlyDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.recentlyDate
     *
     * @return the value of company_transfer.recentlyDate
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public String getRecentlyDate() {
        return recentlyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.recentlyDate
     *
     * @param recentlyDate the value for company_transfer.recentlyDate
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setRecentlyDate(String recentlyDate) {
        this.recentlyDate = recentlyDate == null ? null : recentlyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.yearNum
     *
     * @return the value of company_transfer.yearNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Double getYearNum() {
        return yearNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.yearNum
     *
     * @param yearNum the value for company_transfer.yearNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setYearNum(Double yearNum) {
        this.yearNum = yearNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.repertoryNum
     *
     * @return the value of company_transfer.repertoryNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Double getRepertoryNum() {
        return repertoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.repertoryNum
     *
     * @param repertoryNum the value for company_transfer.repertoryNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setRepertoryNum(Double repertoryNum) {
        this.repertoryNum = repertoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.orderNum
     *
     * @return the value of company_transfer.orderNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.orderNum
     *
     * @param orderNum the value for company_transfer.orderNum
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.createTime
     *
     * @return the value of company_transfer.createTime
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.createTime
     *
     * @param createTime the value for company_transfer.createTime
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_transfer.creator
     *
     * @return the value of company_transfer.creator
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_transfer.creator
     *
     * @param creator the value for company_transfer.creator
     *
     * @mbggenerated Sat Dec 23 22:24:56 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
}