package com.imory.cn.company.dto;

import java.util.Date;

public class OneCompanyOneRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.id
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.fileId
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.companyId
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.companyName
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.area
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Double area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.street
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.address
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.representative
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String representative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.telphone
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.contacter
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String contacter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.contactMobile
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.industry
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.code
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.zip
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.investment
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Double investment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.employee
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Integer employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.documentDate
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Date documentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.createTime
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onecompany_onerecord.creator
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    private Integer creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.id
     *
     * @return the value of onecompany_onerecord.id
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.id
     *
     * @param id the value for onecompany_onerecord.id
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.fileId
     *
     * @return the value of onecompany_onerecord.fileId
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.fileId
     *
     * @param fileId the value for onecompany_onerecord.fileId
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.companyId
     *
     * @return the value of onecompany_onerecord.companyId
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.companyId
     *
     * @param companyId the value for onecompany_onerecord.companyId
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.companyName
     *
     * @return the value of onecompany_onerecord.companyName
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.companyName
     *
     * @param companyName the value for onecompany_onerecord.companyName
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.area
     *
     * @return the value of onecompany_onerecord.area
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.area
     *
     * @param area the value for onecompany_onerecord.area
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.street
     *
     * @return the value of onecompany_onerecord.street
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.street
     *
     * @param street the value for onecompany_onerecord.street
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.address
     *
     * @return the value of onecompany_onerecord.address
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.address
     *
     * @param address the value for onecompany_onerecord.address
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.representative
     *
     * @return the value of onecompany_onerecord.representative
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.representative
     *
     * @param representative the value for onecompany_onerecord.representative
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setRepresentative(String representative) {
        this.representative = representative == null ? null : representative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.telphone
     *
     * @return the value of onecompany_onerecord.telphone
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.telphone
     *
     * @param telphone the value for onecompany_onerecord.telphone
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.contacter
     *
     * @return the value of onecompany_onerecord.contacter
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getContacter() {
        return contacter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.contacter
     *
     * @param contacter the value for onecompany_onerecord.contacter
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setContacter(String contacter) {
        this.contacter = contacter == null ? null : contacter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.contactMobile
     *
     * @return the value of onecompany_onerecord.contactMobile
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.contactMobile
     *
     * @param contactMobile the value for onecompany_onerecord.contactMobile
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.industry
     *
     * @return the value of onecompany_onerecord.industry
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.industry
     *
     * @param industry the value for onecompany_onerecord.industry
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.code
     *
     * @return the value of onecompany_onerecord.code
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.code
     *
     * @param code the value for onecompany_onerecord.code
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.zip
     *
     * @return the value of onecompany_onerecord.zip
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.zip
     *
     * @param zip the value for onecompany_onerecord.zip
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.investment
     *
     * @return the value of onecompany_onerecord.investment
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Double getInvestment() {
        return investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.investment
     *
     * @param investment the value for onecompany_onerecord.investment
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setInvestment(Double investment) {
        this.investment = investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.employee
     *
     * @return the value of onecompany_onerecord.employee
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Integer getEmployee() {
        return employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.employee
     *
     * @param employee the value for onecompany_onerecord.employee
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setEmployee(Integer employee) {
        this.employee = employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.documentDate
     *
     * @return the value of onecompany_onerecord.documentDate
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Date getDocumentDate() {
        return documentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.documentDate
     *
     * @param documentDate the value for onecompany_onerecord.documentDate
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setDocumentDate(Date documentDate) {
        this.documentDate = documentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.createTime
     *
     * @return the value of onecompany_onerecord.createTime
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.createTime
     *
     * @param createTime the value for onecompany_onerecord.createTime
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onecompany_onerecord.creator
     *
     * @return the value of onecompany_onerecord.creator
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onecompany_onerecord.creator
     *
     * @param creator the value for onecompany_onerecord.creator
     *
     * @mbggenerated Sat Dec 23 14:35:53 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
}