package com.imory.cn.company.dto;

import java.util.Date;

public class OrgCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.id
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.logonId
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String logonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.logonPsd
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String logonPsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.companyName
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.state
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.province
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.city
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.code
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.street
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.address
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.createTime
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.updateTime
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.creator
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company.enable
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    private Boolean enable;

    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.id
     *
     * @return the value of org_company.id
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.id
     *
     * @param id the value for org_company.id
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.logonId
     *
     * @return the value of org_company.logonId
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getLogonId() {
        return logonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.logonId
     *
     * @param logonId the value for org_company.logonId
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setLogonId(String logonId) {
        this.logonId = logonId == null ? null : logonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.logonPsd
     *
     * @return the value of org_company.logonPsd
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getLogonPsd() {
        return logonPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.logonPsd
     *
     * @param logonPsd the value for org_company.logonPsd
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setLogonPsd(String logonPsd) {
        this.logonPsd = logonPsd == null ? null : logonPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.companyName
     *
     * @return the value of org_company.companyName
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.companyName
     *
     * @param companyName the value for org_company.companyName
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.state
     *
     * @return the value of org_company.state
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.state
     *
     * @param state the value for org_company.state
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.province
     *
     * @return the value of org_company.province
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.province
     *
     * @param province the value for org_company.province
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.city
     *
     * @return the value of org_company.city
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.city
     *
     * @param city the value for org_company.city
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.code
     *
     * @return the value of org_company.code
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.code
     *
     * @param code the value for org_company.code
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.street
     *
     * @return the value of org_company.street
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.street
     *
     * @param street the value for org_company.street
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.address
     *
     * @return the value of org_company.address
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.address
     *
     * @param address the value for org_company.address
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.createTime
     *
     * @return the value of org_company.createTime
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.createTime
     *
     * @param createTime the value for org_company.createTime
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.updateTime
     *
     * @return the value of org_company.updateTime
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.updateTime
     *
     * @param updateTime the value for org_company.updateTime
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.creator
     *
     * @return the value of org_company.creator
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.creator
     *
     * @param creator the value for org_company.creator
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company.enable
     *
     * @return the value of org_company.enable
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company.enable
     *
     * @param enable the value for org_company.enable
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}