package com.imory.cn.company.dto;

import java.util.Date;

public class OrgCompanyProxies {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company_proxies.id
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company_proxies.orgAccoId
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    private Integer orgAccoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company_proxies.companyId
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column org_company_proxies.createTime
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company_proxies.id
     *
     * @return the value of org_company_proxies.id
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company_proxies.id
     *
     * @param id the value for org_company_proxies.id
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company_proxies.orgAccoId
     *
     * @return the value of org_company_proxies.orgAccoId
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public Integer getOrgAccoId() {
        return orgAccoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company_proxies.orgAccoId
     *
     * @param orgAccoId the value for org_company_proxies.orgAccoId
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public void setOrgAccoId(Integer orgAccoId) {
        this.orgAccoId = orgAccoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company_proxies.companyId
     *
     * @return the value of org_company_proxies.companyId
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company_proxies.companyId
     *
     * @param companyId the value for org_company_proxies.companyId
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column org_company_proxies.createTime
     *
     * @return the value of org_company_proxies.createTime
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column org_company_proxies.createTime
     *
     * @param createTime the value for org_company_proxies.createTime
     *
     * @mbggenerated Wed Dec 13 14:59:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}