package com.imory.cn.menu.dto;

import java.util.Date;
import java.util.List;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.title
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_type
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private String menu_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.display
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Integer display;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Integer parent_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.creator
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.create_time
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.update_user
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Integer update_user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.update_time
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.status
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    private List<Menu> children;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.title
     *
     * @return the value of menu.title
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.title
     *
     * @param title the value for menu.title
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_type
     *
     * @return the value of menu.menu_type
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public String getMenu_type() {
        return menu_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_type
     *
     * @param menu_type the value for menu.menu_type
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setMenu_type(String menu_type) {
        this.menu_type = menu_type == null ? null : menu_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.display
     *
     * @return the value of menu.display
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Integer getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.display
     *
     * @param display the value for menu.display
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setDisplay(Integer display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parent_id the value for menu.parent_id
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.creator
     *
     * @return the value of menu.creator
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.creator
     *
     * @param creator the value for menu.creator
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.create_time
     *
     * @return the value of menu.create_time
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.create_time
     *
     * @param create_time the value for menu.create_time
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.update_user
     *
     * @return the value of menu.update_user
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Integer getUpdate_user() {
        return update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.update_user
     *
     * @param update_user the value for menu.update_user
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setUpdate_user(Integer update_user) {
        this.update_user = update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.update_time
     *
     * @return the value of menu.update_time
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.update_time
     *
     * @param update_time the value for menu.update_time
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.status
     *
     * @return the value of menu.status
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.status
     *
     * @param status the value for menu.status
     *
     * @mbggenerated Tue Dec 05 11:23:19 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public List<Menu> getChildren()
    {
        return children;
    }

    public void setChildren(List<Menu> children)
    {
        this.children = children;
    }
}