package com.imory.cn.userRole.dao;

import com.imory.cn.userRole.dto.UserRole;
import com.imory.cn.userRole.dto.UserRoleExample;
import com.imory.cn.userRole.dto.UserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @SelectProvider(type=UserRoleSqlProvider.class, method="countByExample")
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @DeleteProvider(type=UserRoleSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @Delete({
        "delete from user_role",
        "where userid = #{userid,jdbcType=INTEGER}",
          "and roleid = #{roleid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @Insert({
        "insert into user_role (userid, roleid, ",
        "creator, create_time)",
        "values (#{userid,jdbcType=INTEGER}, #{roleid,jdbcType=INTEGER}, ",
        "#{creator,jdbcType=INTEGER}, #{create_time,jdbcType=TIMESTAMP})"
    })
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @InsertProvider(type=UserRoleSqlProvider.class, method="insertSelective")
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @SelectProvider(type=UserRoleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="roleid", property="roleid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="create_time", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @Select({
        "select",
        "userid, roleid, creator, create_time",
        "from user_role",
        "where userid = #{userid,jdbcType=INTEGER}",
          "and roleid = #{roleid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="roleid", property="roleid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="create_time", jdbcType=JdbcType.TIMESTAMP)
    })
    UserRole selectByPrimaryKey(UserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    @Update({
        "update user_role",
        "set creator = #{creator,jdbcType=INTEGER},",
          "create_time = #{create_time,jdbcType=TIMESTAMP}",
        "where userid = #{userid,jdbcType=INTEGER}",
          "and roleid = #{roleid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserRole record);
}