package com.imory.cn.company.dao;

import com.imory.cn.company.dto.CompanyTransfer;
import com.imory.cn.company.dto.CompanyTransferExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CompanyTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @SelectProvider(type=CompanyTransferSqlProvider.class, method="countByExample")
    int countByExample(CompanyTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @DeleteProvider(type=CompanyTransferSqlProvider.class, method="deleteByExample")
    int deleteByExample(CompanyTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @Delete({
        "delete from company_transfer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @Insert({
        "insert into company_transfer (recentlyNum, recentlyDirection, ",
        "recentlyDate, yearNum, ",
        "repertoryNum, createTime, ",
        "creator)",
        "values (#{recentlyNum,jdbcType=DECIMAL}, #{recentlyDirection,jdbcType=VARCHAR}, ",
        "#{recentlyDate,jdbcType=VARCHAR}, #{yearNum,jdbcType=DECIMAL}, ",
        "#{repertoryNum,jdbcType=DECIMAL}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(CompanyTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @InsertProvider(type=CompanyTransferSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(CompanyTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @SelectProvider(type=CompanyTransferSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="recentlyNum", property="recentlyNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="recentlyDirection", property="recentlyDirection", jdbcType=JdbcType.VARCHAR),
        @Result(column="recentlyDate", property="recentlyDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="yearNum", property="yearNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="repertoryNum", property="repertoryNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER)
    })
    List<CompanyTransfer> selectByExample(CompanyTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @Select({
        "select",
        "id, recentlyNum, recentlyDirection, recentlyDate, yearNum, repertoryNum, createTime, ",
        "creator",
        "from company_transfer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="recentlyNum", property="recentlyNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="recentlyDirection", property="recentlyDirection", jdbcType=JdbcType.VARCHAR),
        @Result(column="recentlyDate", property="recentlyDate", jdbcType=JdbcType.VARCHAR),
        @Result(column="yearNum", property="yearNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="repertoryNum", property="repertoryNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER)
    })
    CompanyTransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @UpdateProvider(type=CompanyTransferSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") CompanyTransfer record, @Param("example") CompanyTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @UpdateProvider(type=CompanyTransferSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") CompanyTransfer record, @Param("example") CompanyTransferExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @UpdateProvider(type=CompanyTransferSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(CompanyTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    @Update({
        "update company_transfer",
        "set recentlyNum = #{recentlyNum,jdbcType=DECIMAL},",
          "recentlyDirection = #{recentlyDirection,jdbcType=VARCHAR},",
          "recentlyDate = #{recentlyDate,jdbcType=VARCHAR},",
          "yearNum = #{yearNum,jdbcType=DECIMAL},",
          "repertoryNum = #{repertoryNum,jdbcType=DECIMAL},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(CompanyTransfer record);
}