package com.imory.cn.company.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.imory.cn.company.dto.CompanyTransfer;
import com.imory.cn.company.dto.CompanyTransferExample.Criteria;
import com.imory.cn.company.dto.CompanyTransferExample.Criterion;
import com.imory.cn.company.dto.CompanyTransferExample;
import java.util.List;
import java.util.Map;

public class CompanyTransferSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String countByExample(CompanyTransferExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("company_transfer");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String deleteByExample(CompanyTransferExample example) {
        BEGIN();
        DELETE_FROM("company_transfer");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String insertSelective(CompanyTransfer record) {
        BEGIN();
        INSERT_INTO("company_transfer");
        
        if (record.getRecentlyNum() != null) {
            VALUES("recentlyNum", "#{recentlyNum,jdbcType=DECIMAL}");
        }
        
        if (record.getRecentlyDirection() != null) {
            VALUES("recentlyDirection", "#{recentlyDirection,jdbcType=VARCHAR}");
        }
        
        if (record.getRecentlyDate() != null) {
            VALUES("recentlyDate", "#{recentlyDate,jdbcType=VARCHAR}");
        }
        
        if (record.getYearNum() != null) {
            VALUES("yearNum", "#{yearNum,jdbcType=DECIMAL}");
        }
        
        if (record.getRepertoryNum() != null) {
            VALUES("repertoryNum", "#{repertoryNum,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreator() != null) {
            VALUES("creator", "#{creator,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String selectByExample(CompanyTransferExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("recentlyNum");
        SELECT("recentlyDirection");
        SELECT("recentlyDate");
        SELECT("yearNum");
        SELECT("repertoryNum");
        SELECT("createTime");
        SELECT("creator");
        FROM("company_transfer");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        CompanyTransfer record = (CompanyTransfer) parameter.get("record");
        CompanyTransferExample example = (CompanyTransferExample) parameter.get("example");
        
        BEGIN();
        UPDATE("company_transfer");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getRecentlyNum() != null) {
            SET("recentlyNum = #{record.recentlyNum,jdbcType=DECIMAL}");
        }
        
        if (record.getRecentlyDirection() != null) {
            SET("recentlyDirection = #{record.recentlyDirection,jdbcType=VARCHAR}");
        }
        
        if (record.getRecentlyDate() != null) {
            SET("recentlyDate = #{record.recentlyDate,jdbcType=VARCHAR}");
        }
        
        if (record.getYearNum() != null) {
            SET("yearNum = #{record.yearNum,jdbcType=DECIMAL}");
        }
        
        if (record.getRepertoryNum() != null) {
            SET("repertoryNum = #{record.repertoryNum,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreator() != null) {
            SET("creator = #{record.creator,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("company_transfer");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("recentlyNum = #{record.recentlyNum,jdbcType=DECIMAL}");
        SET("recentlyDirection = #{record.recentlyDirection,jdbcType=VARCHAR}");
        SET("recentlyDate = #{record.recentlyDate,jdbcType=VARCHAR}");
        SET("yearNum = #{record.yearNum,jdbcType=DECIMAL}");
        SET("repertoryNum = #{record.repertoryNum,jdbcType=DECIMAL}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("creator = #{record.creator,jdbcType=INTEGER}");
        
        CompanyTransferExample example = (CompanyTransferExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    public String updateByPrimaryKeySelective(CompanyTransfer record) {
        BEGIN();
        UPDATE("company_transfer");
        
        if (record.getRecentlyNum() != null) {
            SET("recentlyNum = #{recentlyNum,jdbcType=DECIMAL}");
        }
        
        if (record.getRecentlyDirection() != null) {
            SET("recentlyDirection = #{recentlyDirection,jdbcType=VARCHAR}");
        }
        
        if (record.getRecentlyDate() != null) {
            SET("recentlyDate = #{recentlyDate,jdbcType=VARCHAR}");
        }
        
        if (record.getYearNum() != null) {
            SET("yearNum = #{yearNum,jdbcType=DECIMAL}");
        }
        
        if (record.getRepertoryNum() != null) {
            SET("repertoryNum = #{repertoryNum,jdbcType=DECIMAL}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreator() != null) {
            SET("creator = #{creator,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_transfer
     *
     * @mbggenerated Wed Dec 13 14:56:37 CST 2017
     */
    protected void applyWhere(CompanyTransferExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}