package com.imory.cn.company.dao;

import com.imory.cn.company.dto.OneCompanyOneRecord;
import com.imory.cn.company.dto.OneCompanyOneRecordExample;
import com.imory.cn.company.dto.OneCompanyOneRecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OneCompanyOneRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @SelectProvider(type=OneCompanyOneRecordSqlProvider.class, method="countByExample")
    int countByExample(OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @DeleteProvider(type=OneCompanyOneRecordSqlProvider.class, method="deleteByExample")
    int deleteByExample(OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @Delete({
        "delete from oneCompany_oneRecord",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @Insert({
        "insert into oneCompany_oneRecord (companyId, companyName, ",
        "street, address, ",
        "representative, telphone, ",
        "contacter, contactMobile, ",
        "industry, area, ",
        "code, zip, investment, ",
        "employee, documentDate, ",
        "createTime, creator, ",
        "problem, measure, ",
        "conclusion)",
        "values (#{companyId,jdbcType=INTEGER}, #{companyName,jdbcType=VARCHAR}, ",
        "#{street,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{representative,jdbcType=VARCHAR}, #{telphone,jdbcType=VARCHAR}, ",
        "#{contacter,jdbcType=VARCHAR}, #{contactMobile,jdbcType=VARCHAR}, ",
        "#{industry,jdbcType=VARCHAR}, #{area,jdbcType=DECIMAL}, ",
        "#{code,jdbcType=VARCHAR}, #{zip,jdbcType=VARCHAR}, #{investment,jdbcType=DECIMAL}, ",
        "#{employee,jdbcType=INTEGER}, #{documentDate,jdbcType=DATE}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=INTEGER}, ",
        "#{problem,jdbcType=LONGVARCHAR}, #{measure,jdbcType=LONGVARCHAR}, ",
        "#{conclusion,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OneCompanyOneRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @InsertProvider(type=OneCompanyOneRecordSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(OneCompanyOneRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @SelectProvider(type=OneCompanyOneRecordSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="companyId", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="representative", property="representative", jdbcType=JdbcType.VARCHAR),
        @Result(column="telphone", property="telphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="contacter", property="contacter", jdbcType=JdbcType.VARCHAR),
        @Result(column="contactMobile", property="contactMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="industry", property="industry", jdbcType=JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType=JdbcType.DECIMAL),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="zip", property="zip", jdbcType=JdbcType.VARCHAR),
        @Result(column="investment", property="investment", jdbcType=JdbcType.DECIMAL),
        @Result(column="employee", property="employee", jdbcType=JdbcType.INTEGER),
        @Result(column="documentDate", property="documentDate", jdbcType=JdbcType.DATE),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="problem", property="problem", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="measure", property="measure", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="conclusion", property="conclusion", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<OneCompanyOneRecordWithBLOBs> selectByExampleWithBLOBs(OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @SelectProvider(type=OneCompanyOneRecordSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="companyId", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="representative", property="representative", jdbcType=JdbcType.VARCHAR),
        @Result(column="telphone", property="telphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="contacter", property="contacter", jdbcType=JdbcType.VARCHAR),
        @Result(column="contactMobile", property="contactMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="industry", property="industry", jdbcType=JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType=JdbcType.DECIMAL),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="zip", property="zip", jdbcType=JdbcType.VARCHAR),
        @Result(column="investment", property="investment", jdbcType=JdbcType.DECIMAL),
        @Result(column="employee", property="employee", jdbcType=JdbcType.INTEGER),
        @Result(column="documentDate", property="documentDate", jdbcType=JdbcType.DATE),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER)
    })
    List<OneCompanyOneRecord> selectByExample(OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @Select({
        "select",
        "id, companyId, companyName, street, address, representative, telphone, contacter, ",
        "contactMobile, industry, area, code, zip, investment, employee, documentDate, ",
        "createTime, creator, problem, measure, conclusion",
        "from oneCompany_oneRecord",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="companyId", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="representative", property="representative", jdbcType=JdbcType.VARCHAR),
        @Result(column="telphone", property="telphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="contacter", property="contacter", jdbcType=JdbcType.VARCHAR),
        @Result(column="contactMobile", property="contactMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="industry", property="industry", jdbcType=JdbcType.VARCHAR),
        @Result(column="area", property="area", jdbcType=JdbcType.DECIMAL),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="zip", property="zip", jdbcType=JdbcType.VARCHAR),
        @Result(column="investment", property="investment", jdbcType=JdbcType.DECIMAL),
        @Result(column="employee", property="employee", jdbcType=JdbcType.INTEGER),
        @Result(column="documentDate", property="documentDate", jdbcType=JdbcType.DATE),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="problem", property="problem", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="measure", property="measure", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="conclusion", property="conclusion", jdbcType=JdbcType.LONGVARCHAR)
    })
    OneCompanyOneRecordWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @UpdateProvider(type=OneCompanyOneRecordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OneCompanyOneRecordWithBLOBs record, @Param("example") OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @UpdateProvider(type=OneCompanyOneRecordSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") OneCompanyOneRecordWithBLOBs record, @Param("example") OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @UpdateProvider(type=OneCompanyOneRecordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OneCompanyOneRecord record, @Param("example") OneCompanyOneRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @UpdateProvider(type=OneCompanyOneRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OneCompanyOneRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @Update({
        "update oneCompany_oneRecord",
        "set companyId = #{companyId,jdbcType=INTEGER},",
          "companyName = #{companyName,jdbcType=VARCHAR},",
          "street = #{street,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "representative = #{representative,jdbcType=VARCHAR},",
          "telphone = #{telphone,jdbcType=VARCHAR},",
          "contacter = #{contacter,jdbcType=VARCHAR},",
          "contactMobile = #{contactMobile,jdbcType=VARCHAR},",
          "industry = #{industry,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=DECIMAL},",
          "code = #{code,jdbcType=VARCHAR},",
          "zip = #{zip,jdbcType=VARCHAR},",
          "investment = #{investment,jdbcType=DECIMAL},",
          "employee = #{employee,jdbcType=INTEGER},",
          "documentDate = #{documentDate,jdbcType=DATE},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "problem = #{problem,jdbcType=LONGVARCHAR},",
          "measure = #{measure,jdbcType=LONGVARCHAR},",
          "conclusion = #{conclusion,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(OneCompanyOneRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oneCompany_oneRecord
     *
     * @mbggenerated Wed Dec 13 14:57:48 CST 2017
     */
    @Update({
        "update oneCompany_oneRecord",
        "set companyId = #{companyId,jdbcType=INTEGER},",
          "companyName = #{companyName,jdbcType=VARCHAR},",
          "street = #{street,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "representative = #{representative,jdbcType=VARCHAR},",
          "telphone = #{telphone,jdbcType=VARCHAR},",
          "contacter = #{contacter,jdbcType=VARCHAR},",
          "contactMobile = #{contactMobile,jdbcType=VARCHAR},",
          "industry = #{industry,jdbcType=VARCHAR},",
          "area = #{area,jdbcType=DECIMAL},",
          "code = #{code,jdbcType=VARCHAR},",
          "zip = #{zip,jdbcType=VARCHAR},",
          "investment = #{investment,jdbcType=DECIMAL},",
          "employee = #{employee,jdbcType=INTEGER},",
          "documentDate = #{documentDate,jdbcType=DATE},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OneCompanyOneRecord record);
}