package com.imory.cn.company.dao;

import com.imory.cn.company.dto.OrgCompany;
import com.imory.cn.company.dto.OrgCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrgCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @SelectProvider(type=OrgCompanySqlProvider.class, method="countByExample")
    int countByExample(OrgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @DeleteProvider(type=OrgCompanySqlProvider.class, method="deleteByExample")
    int deleteByExample(OrgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @Delete({
        "delete from org_company",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @Insert({
        "insert into org_company (logonId, logonPsd, ",
        "companyName, state, ",
        "province, city, ",
        "code, street, address, ",
        "createTime, updateTime, ",
        "creator, enable)",
        "values (#{logonId,jdbcType=VARCHAR}, #{logonPsd,jdbcType=VARCHAR}, ",
        "#{companyName,jdbcType=VARCHAR}, #{state,jdbcType=INTEGER}, ",
        "#{province,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{code,jdbcType=VARCHAR}, #{street,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER}, #{enable,jdbcType=BIT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OrgCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @InsertProvider(type=OrgCompanySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(OrgCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @SelectProvider(type=OrgCompanySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="logonId", property="logonId", jdbcType=JdbcType.VARCHAR),
        @Result(column="logonPsd", property="logonPsd", jdbcType=JdbcType.VARCHAR),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="enable", property="enable", jdbcType=JdbcType.BIT)
    })
    List<OrgCompany> selectByExample(OrgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @Select({
        "select",
        "id, logonId, logonPsd, companyName, state, province, city, code, street, address, ",
        "createTime, updateTime, creator, enable",
        "from org_company",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="logonId", property="logonId", jdbcType=JdbcType.VARCHAR),
        @Result(column="logonPsd", property="logonPsd", jdbcType=JdbcType.VARCHAR),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="street", property="street", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="enable", property="enable", jdbcType=JdbcType.BIT)
    })
    OrgCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @UpdateProvider(type=OrgCompanySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrgCompany record, @Param("example") OrgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @UpdateProvider(type=OrgCompanySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrgCompany record, @Param("example") OrgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @UpdateProvider(type=OrgCompanySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrgCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_company
     *
     * @mbggenerated Thu Dec 14 21:03:16 CST 2017
     */
    @Update({
        "update org_company",
        "set logonId = #{logonId,jdbcType=VARCHAR},",
          "logonPsd = #{logonPsd,jdbcType=VARCHAR},",
          "companyName = #{companyName,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER},",
          "province = #{province,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "code = #{code,jdbcType=VARCHAR},",
          "street = #{street,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "enable = #{enable,jdbcType=BIT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrgCompany record);
}