package com.imory.cn.excel.dto;

import java.util.Date;

public class ExcelFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.id
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.companyId
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.fileName
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.fileName_bk
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private String fileName_bk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.fileDate
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Date fileDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.fileUrl
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.fileUrlBak
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private String fileUrlBak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.filePath
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.state
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.createTime
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.updateTime
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.creator
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column excel_file.updateor
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    private Integer updateor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.id
     *
     * @return the value of excel_file.id
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.id
     *
     * @param id the value for excel_file.id
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.companyId
     *
     * @return the value of excel_file.companyId
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.companyId
     *
     * @param companyId the value for excel_file.companyId
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.fileName
     *
     * @return the value of excel_file.fileName
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.fileName
     *
     * @param fileName the value for excel_file.fileName
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.fileName_bk
     *
     * @return the value of excel_file.fileName_bk
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public String getFileName_bk() {
        return fileName_bk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.fileName_bk
     *
     * @param fileName_bk the value for excel_file.fileName_bk
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setFileName_bk(String fileName_bk) {
        this.fileName_bk = fileName_bk == null ? null : fileName_bk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.fileDate
     *
     * @return the value of excel_file.fileDate
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Date getFileDate() {
        return fileDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.fileDate
     *
     * @param fileDate the value for excel_file.fileDate
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setFileDate(Date fileDate) {
        this.fileDate = fileDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.fileUrl
     *
     * @return the value of excel_file.fileUrl
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.fileUrl
     *
     * @param fileUrl the value for excel_file.fileUrl
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.fileUrlBak
     *
     * @return the value of excel_file.fileUrlBak
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public String getFileUrlBak() {
        return fileUrlBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.fileUrlBak
     *
     * @param fileUrlBak the value for excel_file.fileUrlBak
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setFileUrlBak(String fileUrlBak) {
        this.fileUrlBak = fileUrlBak == null ? null : fileUrlBak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.filePath
     *
     * @return the value of excel_file.filePath
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.filePath
     *
     * @param filePath the value for excel_file.filePath
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.state
     *
     * @return the value of excel_file.state
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.state
     *
     * @param state the value for excel_file.state
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.createTime
     *
     * @return the value of excel_file.createTime
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.createTime
     *
     * @param createTime the value for excel_file.createTime
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.updateTime
     *
     * @return the value of excel_file.updateTime
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.updateTime
     *
     * @param updateTime the value for excel_file.updateTime
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.creator
     *
     * @return the value of excel_file.creator
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.creator
     *
     * @param creator the value for excel_file.creator
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column excel_file.updateor
     *
     * @return the value of excel_file.updateor
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public Integer getUpdateor() {
        return updateor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column excel_file.updateor
     *
     * @param updateor the value for excel_file.updateor
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    public void setUpdateor(Integer updateor) {
        this.updateor = updateor;
    }
}