package com.imory.cn.roleMenu.dto;

import java.util.Date;

public class RoleMenu extends RoleMenuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.flag
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.creator
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.create_time
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.flag
     *
     * @return the value of role_menu.flag
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.flag
     *
     * @param flag the value for role_menu.flag
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.creator
     *
     * @return the value of role_menu.creator
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.creator
     *
     * @param creator the value for role_menu.creator
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.create_time
     *
     * @return the value of role_menu.create_time
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.create_time
     *
     * @param create_time the value for role_menu.create_time
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}