package com.imory.cn.roleMenu.dto;

public class RoleMenuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menuid
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.roleid
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menuid
     *
     * @return the value of role_menu.menuid
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menuid
     *
     * @param menuid the value for role_menu.menuid
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.roleid
     *
     * @return the value of role_menu.roleid
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.roleid
     *
     * @param roleid the value for role_menu.roleid
     *
     * @mbggenerated Tue Dec 05 13:14:08 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}