package com.imory.cn.org.dao;

import com.imory.cn.org.dto.OrgaccountInfo;
import com.imory.cn.org.dto.OrgaccountInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrgaccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @SelectProvider(type=OrgaccountInfoSqlProvider.class, method="countByExample")
    int countByExample(OrgaccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @DeleteProvider(type=OrgaccountInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrgaccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @Delete({
        "delete from orgaccountinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @Insert({
        "insert into orgaccountinfo (logonId, logonPsd, ",
        "userName, openId, ",
        "email, mobile, state, ",
        "companyName, registerDate, ",
        "createTime)",
        "values (#{logonId,jdbcType=VARCHAR}, #{logonPsd,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{openId,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, #{state,jdbcType=INTEGER}, ",
        "#{companyName,jdbcType=VARCHAR}, #{registerDate,jdbcType=TIMESTAMP}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OrgaccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @InsertProvider(type=OrgaccountInfoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(OrgaccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @SelectProvider(type=OrgaccountInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="logonId", property="logonId", jdbcType=JdbcType.VARCHAR),
        @Result(column="logonPsd", property="logonPsd", jdbcType=JdbcType.VARCHAR),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="openId", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="registerDate", property="registerDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<OrgaccountInfo> selectByExample(OrgaccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @Select({
        "select",
        "id, logonId, logonPsd, userName, openId, email, mobile, state, companyName, ",
        "registerDate, createTime",
        "from orgaccountinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="logonId", property="logonId", jdbcType=JdbcType.VARCHAR),
        @Result(column="logonPsd", property="logonPsd", jdbcType=JdbcType.VARCHAR),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="openId", property="openId", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="mobile", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="companyName", property="companyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="registerDate", property="registerDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    OrgaccountInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @UpdateProvider(type=OrgaccountInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrgaccountInfo record, @Param("example") OrgaccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @UpdateProvider(type=OrgaccountInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrgaccountInfo record, @Param("example") OrgaccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @UpdateProvider(type=OrgaccountInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrgaccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    @Update({
        "update orgaccountinfo",
        "set logonId = #{logonId,jdbcType=VARCHAR},",
          "logonPsd = #{logonPsd,jdbcType=VARCHAR},",
          "userName = #{userName,jdbcType=VARCHAR},",
          "openId = #{openId,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER},",
          "companyName = #{companyName,jdbcType=VARCHAR},",
          "registerDate = #{registerDate,jdbcType=TIMESTAMP},",
          "createTime = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrgaccountInfo record);
}