package com.imory.cn.org.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.imory.cn.org.dto.OrgAccountInfo;
import com.imory.cn.org.dto.OrgAccountInfoExample.Criteria;
import com.imory.cn.org.dto.OrgAccountInfoExample.Criterion;
import com.imory.cn.org.dto.OrgAccountInfoExample;
import java.util.List;
import java.util.Map;

public class OrgAccountInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String countByExample(OrgAccountInfoExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("orgaccountinfo");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String deleteByExample(OrgAccountInfoExample example) {
        BEGIN();
        DELETE_FROM("orgaccountinfo");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String insertSelective(OrgAccountInfo record) {
        BEGIN();
        INSERT_INTO("orgaccountinfo");
        
        if (record.getUserName() != null) {
            VALUES("userName", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenId() != null) {
            VALUES("openId", "#{openId,jdbcType=VARCHAR}");
        }
        
        if (record.getCompanyId() != null) {
            VALUES("companyId", "#{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getNickName() != null) {
            VALUES("nickName", "#{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getLogoUrl() != null) {
            VALUES("logoUrl", "#{logoUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String selectByExample(OrgAccountInfoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("userName");
        SELECT("openId");
        SELECT("companyId");
        SELECT("nickName");
        SELECT("logoUrl");
        SELECT("createTime");
        FROM("orgaccountinfo");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OrgAccountInfo record = (OrgAccountInfo) parameter.get("record");
        OrgAccountInfoExample example = (OrgAccountInfoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("orgaccountinfo");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUserName() != null) {
            SET("userName = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenId() != null) {
            SET("openId = #{record.openId,jdbcType=VARCHAR}");
        }
        
        if (record.getCompanyId() != null) {
            SET("companyId = #{record.companyId,jdbcType=INTEGER}");
        }
        
        if (record.getNickName() != null) {
            SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getLogoUrl() != null) {
            SET("logoUrl = #{record.logoUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("orgaccountinfo");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("userName = #{record.userName,jdbcType=VARCHAR}");
        SET("openId = #{record.openId,jdbcType=VARCHAR}");
        SET("companyId = #{record.companyId,jdbcType=INTEGER}");
        SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        SET("logoUrl = #{record.logoUrl,jdbcType=VARCHAR}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        
        OrgAccountInfoExample example = (OrgAccountInfoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    public String updateByPrimaryKeySelective(OrgAccountInfo record) {
        BEGIN();
        UPDATE("orgaccountinfo");
        
        if (record.getUserName() != null) {
            SET("userName = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenId() != null) {
            SET("openId = #{openId,jdbcType=VARCHAR}");
        }
        
        if (record.getCompanyId() != null) {
            SET("companyId = #{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getNickName() != null) {
            SET("nickName = #{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getLogoUrl() != null) {
            SET("logoUrl = #{logoUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orgaccountinfo
     *
     * @mbggenerated Sun Jan 07 16:11:52 CST 2018
     */
    protected void applyWhere(OrgAccountInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}