package com.imory.cn.excel.dao;

import com.imory.cn.excel.dto.ExcelFile;
import com.imory.cn.excel.dto.ExcelFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ExcelFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @SelectProvider(type=ExcelFileSqlProvider.class, method="countByExample")
    int countByExample(ExcelFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @DeleteProvider(type=ExcelFileSqlProvider.class, method="deleteByExample")
    int deleteByExample(ExcelFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @Delete({
        "delete from excel_file",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @Insert({
        "insert into excel_file (companyId, fileName, ",
        "fileName_bk, fileDate, ",
        "fileUrl, fileUrlBak, ",
        "filePath, state, ",
        "createTime, updateTime, ",
        "creator, updateor)",
        "values (#{companyId,jdbcType=INTEGER}, #{fileName,jdbcType=VARCHAR}, ",
        "#{fileName_bk,jdbcType=VARCHAR}, #{fileDate,jdbcType=DATE}, ",
        "#{fileUrl,jdbcType=VARCHAR}, #{fileUrlBak,jdbcType=VARCHAR}, ",
        "#{filePath,jdbcType=VARCHAR}, #{state,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER}, #{updateor,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ExcelFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @InsertProvider(type=ExcelFileSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(ExcelFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @SelectProvider(type=ExcelFileSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="companyId", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="fileName", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="fileName_bk", property="fileName_bk", jdbcType=JdbcType.VARCHAR),
        @Result(column="fileDate", property="fileDate", jdbcType=JdbcType.DATE),
        @Result(column="fileUrl", property="fileUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="fileUrlBak", property="fileUrlBak", jdbcType=JdbcType.VARCHAR),
        @Result(column="filePath", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="updateor", property="updateor", jdbcType=JdbcType.INTEGER)
    })
    List<ExcelFile> selectByExample(ExcelFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @Select({
        "select",
        "id, companyId, fileName, fileName_bk, fileDate, fileUrl, fileUrlBak, filePath, ",
        "state, createTime, updateTime, creator, updateor",
        "from excel_file",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="companyId", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="fileName", property="fileName", jdbcType=JdbcType.VARCHAR),
        @Result(column="fileName_bk", property="fileName_bk", jdbcType=JdbcType.VARCHAR),
        @Result(column="fileDate", property="fileDate", jdbcType=JdbcType.DATE),
        @Result(column="fileUrl", property="fileUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="fileUrlBak", property="fileUrlBak", jdbcType=JdbcType.VARCHAR),
        @Result(column="filePath", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="updateor", property="updateor", jdbcType=JdbcType.INTEGER)
    })
    ExcelFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @UpdateProvider(type=ExcelFileSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ExcelFile record, @Param("example") ExcelFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @UpdateProvider(type=ExcelFileSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ExcelFile record, @Param("example") ExcelFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @UpdateProvider(type=ExcelFileSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ExcelFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Fri Dec 15 21:07:41 CST 2017
     */
    @Update({
        "update excel_file",
        "set companyId = #{companyId,jdbcType=INTEGER},",
          "fileName = #{fileName,jdbcType=VARCHAR},",
          "fileName_bk = #{fileName_bk,jdbcType=VARCHAR},",
          "fileDate = #{fileDate,jdbcType=DATE},",
          "fileUrl = #{fileUrl,jdbcType=VARCHAR},",
          "fileUrlBak = #{fileUrlBak,jdbcType=VARCHAR},",
          "filePath = #{filePath,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=INTEGER},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "updateor = #{updateor,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ExcelFile record);
}