package com.imory.cn.excel.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.imory.cn.excel.dto.ExcelFile;
import com.imory.cn.excel.dto.ExcelFileExample.Criteria;
import com.imory.cn.excel.dto.ExcelFileExample.Criterion;
import com.imory.cn.excel.dto.ExcelFileExample;
import java.util.List;
import java.util.Map;

public class ExcelFileSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String countByExample(ExcelFileExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("excel_file");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String deleteByExample(ExcelFileExample example) {
        BEGIN();
        DELETE_FROM("excel_file");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String insertSelective(ExcelFile record) {
        BEGIN();
        INSERT_INTO("excel_file");
        
        if (record.getCompanyId() != null) {
            VALUES("companyId", "#{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getFileName() != null) {
            VALUES("fileName", "#{fileName,jdbcType=VARCHAR}");
        }
        
        if (record.getFileName_bk() != null) {
            VALUES("fileName_bk", "#{fileName_bk,jdbcType=VARCHAR}");
        }
        
        if (record.getFileDate() != null) {
            VALUES("fileDate", "#{fileDate,jdbcType=DATE}");
        }
        
        if (record.getFileUrl() != null) {
            VALUES("fileUrl", "#{fileUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getFileUrlBak() != null) {
            VALUES("fileUrlBak", "#{fileUrlBak,jdbcType=VARCHAR}");
        }
        
        if (record.getFileCompanyUrl() != null) {
            VALUES("fileCompanyUrl", "#{fileCompanyUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getFilePath() != null) {
            VALUES("filePath", "#{filePath,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            VALUES("state", "#{state,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("updateTime", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreator() != null) {
            VALUES("creator", "#{creator,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateor() != null) {
            VALUES("updateor", "#{updateor,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String selectByExample(ExcelFileExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("companyId");
        SELECT("fileName");
        SELECT("fileName_bk");
        SELECT("fileDate");
        SELECT("fileUrl");
        SELECT("fileUrlBak");
        SELECT("fileCompanyUrl");
        SELECT("filePath");
        SELECT("state");
        SELECT("createTime");
        SELECT("updateTime");
        SELECT("creator");
        SELECT("updateor");
        FROM("excel_file");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ExcelFile record = (ExcelFile) parameter.get("record");
        ExcelFileExample example = (ExcelFileExample) parameter.get("example");
        
        BEGIN();
        UPDATE("excel_file");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            SET("companyId = #{record.companyId,jdbcType=INTEGER}");
        }
        
        if (record.getFileName() != null) {
            SET("fileName = #{record.fileName,jdbcType=VARCHAR}");
        }
        
        if (record.getFileName_bk() != null) {
            SET("fileName_bk = #{record.fileName_bk,jdbcType=VARCHAR}");
        }
        
        if (record.getFileDate() != null) {
            SET("fileDate = #{record.fileDate,jdbcType=DATE}");
        }
        
        if (record.getFileUrl() != null) {
            SET("fileUrl = #{record.fileUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getFileUrlBak() != null) {
            SET("fileUrlBak = #{record.fileUrlBak,jdbcType=VARCHAR}");
        }
        
        if (record.getFileCompanyUrl() != null) {
            SET("fileCompanyUrl = #{record.fileCompanyUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getFilePath() != null) {
            SET("filePath = #{record.filePath,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            SET("state = #{record.state,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("updateTime = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreator() != null) {
            SET("creator = #{record.creator,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateor() != null) {
            SET("updateor = #{record.updateor,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("excel_file");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("companyId = #{record.companyId,jdbcType=INTEGER}");
        SET("fileName = #{record.fileName,jdbcType=VARCHAR}");
        SET("fileName_bk = #{record.fileName_bk,jdbcType=VARCHAR}");
        SET("fileDate = #{record.fileDate,jdbcType=DATE}");
        SET("fileUrl = #{record.fileUrl,jdbcType=VARCHAR}");
        SET("fileUrlBak = #{record.fileUrlBak,jdbcType=VARCHAR}");
        SET("fileCompanyUrl = #{record.fileCompanyUrl,jdbcType=VARCHAR}");
        SET("filePath = #{record.filePath,jdbcType=VARCHAR}");
        SET("state = #{record.state,jdbcType=INTEGER}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("updateTime = #{record.updateTime,jdbcType=TIMESTAMP}");
        SET("creator = #{record.creator,jdbcType=INTEGER}");
        SET("updateor = #{record.updateor,jdbcType=INTEGER}");
        
        ExcelFileExample example = (ExcelFileExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    public String updateByPrimaryKeySelective(ExcelFile record) {
        BEGIN();
        UPDATE("excel_file");
        
        if (record.getCompanyId() != null) {
            SET("companyId = #{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getFileName() != null) {
            SET("fileName = #{fileName,jdbcType=VARCHAR}");
        }
        
        if (record.getFileName_bk() != null) {
            SET("fileName_bk = #{fileName_bk,jdbcType=VARCHAR}");
        }
        
        if (record.getFileDate() != null) {
            SET("fileDate = #{fileDate,jdbcType=DATE}");
        }
        
        if (record.getFileUrl() != null) {
            SET("fileUrl = #{fileUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getFileUrlBak() != null) {
            SET("fileUrlBak = #{fileUrlBak,jdbcType=VARCHAR}");
        }
        
        if (record.getFileCompanyUrl() != null) {
            SET("fileCompanyUrl = #{fileCompanyUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getFilePath() != null) {
            SET("filePath = #{filePath,jdbcType=VARCHAR}");
        }
        
        if (record.getState() != null) {
            SET("state = #{state,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("updateTime = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreator() != null) {
            SET("creator = #{creator,jdbcType=INTEGER}");
        }
        
        if (record.getUpdateor() != null) {
            SET("updateor = #{updateor,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel_file
     *
     * @mbggenerated Sat Dec 23 23:12:10 CST 2017
     */
    protected void applyWhere(ExcelFileExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}