package com.imory.cn.org.dto;

import java.util.Date;

public class OrgaccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.id
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.logonId
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String logonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.logonPsd
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String logonPsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.userName
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.openId
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.email
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.mobile
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.state
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.companyName
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.registerDate
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.createTime
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.id
     *
     * @return the value of orgaccountinfo.id
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.id
     *
     * @param id the value for orgaccountinfo.id
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.logonId
     *
     * @return the value of orgaccountinfo.logonId
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getLogonId() {
        return logonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.logonId
     *
     * @param logonId the value for orgaccountinfo.logonId
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setLogonId(String logonId) {
        this.logonId = logonId == null ? null : logonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.logonPsd
     *
     * @return the value of orgaccountinfo.logonPsd
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getLogonPsd() {
        return logonPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.logonPsd
     *
     * @param logonPsd the value for orgaccountinfo.logonPsd
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setLogonPsd(String logonPsd) {
        this.logonPsd = logonPsd == null ? null : logonPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.userName
     *
     * @return the value of orgaccountinfo.userName
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.userName
     *
     * @param userName the value for orgaccountinfo.userName
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.openId
     *
     * @return the value of orgaccountinfo.openId
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.openId
     *
     * @param openId the value for orgaccountinfo.openId
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.email
     *
     * @return the value of orgaccountinfo.email
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.email
     *
     * @param email the value for orgaccountinfo.email
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.mobile
     *
     * @return the value of orgaccountinfo.mobile
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.mobile
     *
     * @param mobile the value for orgaccountinfo.mobile
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.state
     *
     * @return the value of orgaccountinfo.state
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.state
     *
     * @param state the value for orgaccountinfo.state
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.companyName
     *
     * @return the value of orgaccountinfo.companyName
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.companyName
     *
     * @param companyName the value for orgaccountinfo.companyName
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.registerDate
     *
     * @return the value of orgaccountinfo.registerDate
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.registerDate
     *
     * @param registerDate the value for orgaccountinfo.registerDate
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.createTime
     *
     * @return the value of orgaccountinfo.createTime
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.createTime
     *
     * @param createTime the value for orgaccountinfo.createTime
     *
     * @mbggenerated Wed Dec 13 14:54:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}