package com.imory.cn.menu.dao;

import com.imory.cn.menu.dto.Menu;
import com.imory.cn.menu.dto.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @SelectProvider(type=MenuSqlProvider.class, method="countByExample")
    int countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @DeleteProvider(type=MenuSqlProvider.class, method="deleteByExample")
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @Delete({
        "delete from menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @Insert({
        "insert into menu (title, url, ",
        "icon, menu_type, display, ",
        "parent_id, creator, ",
        "create_time, update_user, ",
        "update_time, status, ",
        "level)",
        "values (#{title,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{icon,jdbcType=VARCHAR}, #{menu_type,jdbcType=CHAR}, #{display,jdbcType=INTEGER}, ",
        "#{parent_id,jdbcType=INTEGER}, #{creator,jdbcType=INTEGER}, ",
        "#{create_time,jdbcType=TIMESTAMP}, #{update_user,jdbcType=INTEGER}, ",
        "#{update_time,jdbcType=TIMESTAMP}, #{status,jdbcType=CHAR}, ",
        "#{level,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @InsertProvider(type=MenuSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @SelectProvider(type=MenuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="menu_type", property="menu_type", jdbcType=JdbcType.CHAR),
        @Result(column="display", property="display", jdbcType=JdbcType.INTEGER),
        @Result(column="parent_id", property="parent_id", jdbcType=JdbcType.INTEGER),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="create_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="update_user", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="update_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER)
    })
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @Select({
        "select",
        "id, title, url, icon, menu_type, display, parent_id, creator, create_time, update_user, ",
        "update_time, status, level",
        "from menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="menu_type", property="menu_type", jdbcType=JdbcType.CHAR),
        @Result(column="display", property="display", jdbcType=JdbcType.INTEGER),
        @Result(column="parent_id", property="parent_id", jdbcType=JdbcType.INTEGER),
        @Result(column="creator", property="creator", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="create_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_user", property="update_user", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="update_time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER)
    })
    Menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @UpdateProvider(type=MenuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @UpdateProvider(type=MenuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @UpdateProvider(type=MenuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Wed Dec 06 13:59:03 CST 2017
     */
    @Update({
        "update menu",
        "set title = #{title,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "icon = #{icon,jdbcType=VARCHAR},",
          "menu_type = #{menu_type,jdbcType=CHAR},",
          "display = #{display,jdbcType=INTEGER},",
          "parent_id = #{parent_id,jdbcType=INTEGER},",
          "creator = #{creator,jdbcType=INTEGER},",
          "create_time = #{create_time,jdbcType=TIMESTAMP},",
          "update_user = #{update_user,jdbcType=INTEGER},",
          "update_time = #{update_time,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=CHAR},",
          "level = #{level,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Menu record);
}