package com.imory.cn.userRole.dto;

public class UserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.userid
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.roleid
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.userid
     *
     * @return the value of user_role.userid
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.userid
     *
     * @param userid the value for user_role.userid
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.roleid
     *
     * @return the value of user_role.roleid
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.roleid
     *
     * @param roleid the value for user_role.roleid
     *
     * @mbggenerated Tue Dec 05 13:15:26 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}