package com.imory.cn.user.dto;

import java.util.Date;

public class UserInform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.id
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.creator
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.title
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.openId
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.nickName
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.logoUrl
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.content
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.state
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.replayContent
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String replayContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.replayDate
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private Date replayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.createTime
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.imgUrl
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.id
     *
     * @return the value of user_inform.id
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.id
     *
     * @param id the value for user_inform.id
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.creator
     *
     * @return the value of user_inform.creator
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.creator
     *
     * @param creator the value for user_inform.creator
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.title
     *
     * @return the value of user_inform.title
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.title
     *
     * @param title the value for user_inform.title
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.openId
     *
     * @return the value of user_inform.openId
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.openId
     *
     * @param openId the value for user_inform.openId
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.nickName
     *
     * @return the value of user_inform.nickName
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.nickName
     *
     * @param nickName the value for user_inform.nickName
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.logoUrl
     *
     * @return the value of user_inform.logoUrl
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.logoUrl
     *
     * @param logoUrl the value for user_inform.logoUrl
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.content
     *
     * @return the value of user_inform.content
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.content
     *
     * @param content the value for user_inform.content
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.state
     *
     * @return the value of user_inform.state
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.state
     *
     * @param state the value for user_inform.state
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.replayContent
     *
     * @return the value of user_inform.replayContent
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getReplayContent() {
        return replayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.replayContent
     *
     * @param replayContent the value for user_inform.replayContent
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setReplayContent(String replayContent) {
        this.replayContent = replayContent == null ? null : replayContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.replayDate
     *
     * @return the value of user_inform.replayDate
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public Date getReplayDate() {
        return replayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.replayDate
     *
     * @param replayDate the value for user_inform.replayDate
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setReplayDate(Date replayDate) {
        this.replayDate = replayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.createTime
     *
     * @return the value of user_inform.createTime
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.createTime
     *
     * @param createTime the value for user_inform.createTime
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.imgUrl
     *
     * @return the value of user_inform.imgUrl
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.imgUrl
     *
     * @param imgUrl the value for user_inform.imgUrl
     *
     * @mbggenerated Sun Dec 24 13:48:08 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}